package luaj;

import android.ext.HexText;
import android.ext.Log;
import android.ext.ToolsLight;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintStream;

public class Print extends Lua {
    static class PrintState {
        int func;
        String level;
        int line;
        byte[] used;

        PrintState() {
            this.func = 0;
            this.line = -1;
        }
    }

    private static final byte BRANCH = 2;
    private static final int ERR_OP_LOADKX_NOT_OP_EXTRAARG = 0x7FFFFFFE;
    private static final int ERR_OP_LOADKX_NO_NEXT = 0x7FFFFFFF;
    public static final String HEADER = "; --[=========[ Lua assembler file generated by GameGuardian ";
    private static final byte NEED_LABEL = 0x20;
    private static final byte NONE = 0;
    private static final int NOP = 0;
    public static final String[] OPNAMES = null;
    private static final String STRING_FOR_NULL = "null";
    private static final byte TARGET = 0x40;
    private static final byte UNUSED = 3;
    private static final byte USED = 1;
    private static final byte USED_MASK = 0x1F;
    public static PrintStream ps;

    static {
        Print.ps = System.out;
        Print.OPNAMES = new String[]{"MOVE", "LOADK", "LOADKX", "LOADBOOL", "LOADNIL", "GETUPVAL", "GETTABUP", "GETTABLE", "SETTABUP", "SETUPVAL", "SETTABLE", "NEWTABLE", "SELF", "ADD", "SUB", "MUL", "DIV", "MOD", "POW", "UNM", "NOT", "LEN", "CONCAT", "JMP", "EQ", "LT", "LE", "TEST", "TESTSET", "CALL", "TAILCALL", "RETURN", "FORLOOP", "FORPREP", "TFORCALL", "TFORLOOP", "SETLIST", "CLOSURE", "VARARG", "EXTRAARG", "IDIV", "BNOT", "BAND", "BOR", "BXOR", "SHL", "SHR", null};
        Print.NOP = 0x80001F;
    }

    private static StringBuilder addComm(StringBuilder comm, String str) {
        if(comm == null) {
            comm = new StringBuilder(str.length() + 2);
        }
        comm.append("; ");
        comm.append(str);
        return comm;
    }

    private static StringBuilder checkUp(StringBuilder comm, int upmax, int var) {
        return var < upmax ? comm : Print.addComm(comm, "upvalue u" + var + " out of upvalues list (" + upmax + " upvalues for this func)");
    }

    private static StringBuilder checkVar(StringBuilder comm, int max, int var) {
        if(var < 0) {
            return Print.addComm(comm, "impossible (negative) variable v" + var);
        }
        return var < max ? comm : Print.addComm(comm, "variable v" + var + " out of stack (.maxstacksize = " + max + " for this func)");
    }

    static void describe(StringBuilder sb, int pc, int i) {
        int v2 = Print.GET_OPCODE(i);
        int v3 = Print.GETARG_A(i);
        int v4 = Print.GETARG_B(i);
        int v5 = Print.GETARG_C(i);
        int v6 = Print.GETARG_Bx(i);
        int v7 = Print.GETARG_sBx(i);
        sb.append(" ; PC ");
        sb.append(pc);
        sb.append(" CODE ");
        ToolsLight.prefixIntegerHex(sb, 8, i);
        sb.append(" OP ");
        sb.append(v2);
        sb.append(" A ");
        sb.append(v3);
        sb.append(" B ");
        sb.append(v4);
        sb.append(" C ");
        sb.append(v5);
        sb.append(" Bx ");
        sb.append(v6);
        sb.append(" sBx ");
        sb.append(v7);
    }

    private static boolean fix(byte[] used, Prototype f, int[] code, int[] fixed) {
        boolean changed = false;
        int maxOp = Print.OPNAMES.length - 1;
        int maxConst = f.k.length;
        int maxVars = f.maxstacksize;
        int entry = 0;
        do {
            int pc = entry;
            while(pc >= 0 && pc < code.length) {
                int u = (byte)(used[pc] & 0x1F);
                if(u == 1) {
                    break;
                }
                used[pc] = (byte)(used[pc] + (1 - u));
                int i = code[pc];
                int orig = i;
                int orig_pc = pc;
                int v9 = Print.GET_OPCODE(i);
                if(v9 >= maxOp) {
                    i = Print.NOP;
                }
                else {
                    int v10 = Print.GETARG_A(i);
                    int v11 = Print.GETARG_B(i);
                    int v12 = Print.GETARG_C(i);
                    int v13 = Print.GETARG_Bx(i);
                    int v14 = Print.GETARG_sBx(i);
                alab1:
                    switch(Print.getOpMode(v9)) {
                        case 0: {
                            switch(v9) {
                                case 8: {
                                    if(v10 >= f.upvalues.length) {
                                        i = Print.NOP;
                                    }
                                    break;
                                }
                                case 24: 
                                case 25: 
                                case 26: {
                                    break;
                                }
                                default: {
                                    if(v10 >= maxVars) {
                                        i = Print.NOP;
                                    }
                                }
                            }
                            switch(v9) {
                                case 4: {
                                    if(v10 + v11 >= maxVars) {
                                        i = Print.NOP;
                                    }
                                    break alab1;
                                }
                                case 34: {
                                    if(v10 + v12 + 2 >= maxVars) {
                                        i = Print.NOP;
                                    }
                                    break alab1;
                                }
                                case 36: {
                                    if(v10 + v11 >= maxVars) {
                                        i = Print.NOP;
                                    }
                                    else if(v12 == 0) {
                                        if(pc == code.length - 1) {
                                            i = Print.NOP;
                                        }
                                        else {
                                            ++pc;
                                            used[pc] = (byte)((used[pc] & 0xFFFFFFE0) + 1);
                                        }
                                    }
                                    break alab1;
                                }
                                case 29: 
                                case 30: 
                                case 0x1F: 
                                case 38: {
                                    if(v11 > 0 && v10 + v11 - (v9 == 0x1F ? 2 : 1) >= maxVars) {
                                        i = Print.NOP;
                                    }
                                    if(v9 == 30 || v9 == 0x1F) {
                                        pc = entry - 1;
                                    }
                                    if(v9 == 29 && v12 > 1 && (v10 >= maxVars || v10 + v12 - 2 >= maxVars)) {
                                        i = Print.NOP;
                                    }
                                    break alab1;
                                }
                                default: {
                                    int v15 = Print.getBMode(v9);
                                    if(v15 != 0) {
                                        if(v15 != 3 || !Print.ISK(v11)) {
                                            if(v9 != 3 && v9 != 11) {
                                                if(v15 != 1) {
                                                    if(v11 >= maxVars) {
                                                        i = Print.NOP;
                                                    }
                                                }
                                                else if(v11 >= f.upvalues.length) {
                                                    i = Print.NOP;
                                                }
                                            }
                                        }
                                        else if(Print.INDEXK(v11) >= maxConst) {
                                            i = Print.NOP;
                                        }
                                    }
                                    int v16 = Print.getCMode(v9);
                                    if(v16 != 0) {
                                        if(v16 != 3 || !Print.ISK(v12)) {
                                            if(v16 != 1 && v12 >= maxVars) {
                                                i = Print.NOP;
                                            }
                                        }
                                        else if(Print.INDEXK(v12) >= maxConst) {
                                            i = Print.NOP;
                                        }
                                    }
                                    switch(v9) {
                                        case 3: {
                                            if(v12 != 0) {
                                                goto label_55;
                                            }
                                            break alab1;
                                        }
                                        case 24: 
                                        case 25: 
                                        case 26: 
                                        case 27: 
                                        case 28: {
                                        label_55:
                                            if(i != Print.NOP && (used[pc + 2] & 0x1F) == 0) {
                                                used[pc + 2] = (byte)(used[pc + 2] + 2 | 0x40);
                                            }
                                            break alab1;
                                        }
                                        default: {
                                            break alab1;
                                        }
                                    }
                                }
                            }
                        }
                        case 1: {
                            switch(v9) {
                                case 1: {
                                    if(v10 >= maxVars || v13 >= maxConst) {
                                        i = Print.NOP;
                                    }
                                    break alab1;
                                }
                                case 2: {
                                    if(v10 >= maxVars || pc == code.length - 1 || Print.GET_OPCODE(code[pc + 1]) != 39 || Print.GETARG_Ax(code[pc + 1]) >= maxConst) {
                                        i = Print.NOP;
                                    }
                                    break alab1;
                                }
                                case 37: {
                                    if(v10 >= maxVars || v13 >= f.p.length) {
                                        i = Print.NOP;
                                    }
                                    break alab1;
                                }
                                default: {
                                    break alab1;
                                }
                            }
                        }
                        case 2: {
                            switch(v9) {
                                case 0x20: 
                                case 33: {
                                    if(v10 >= maxVars - 2) {
                                        i = Print.NOP;
                                    }
                                    break;
                                }
                                case 35: {
                                    if(v10 >= maxVars - 1) {
                                        i = Print.NOP;
                                    }
                                }
                            }
                            int to = v14 + pc + 1;
                            if(to >= 0 && to < code.length) {
                                if(i != Print.NOP) {
                                    if(v9 == 23) {
                                        pc = to - 1;
                                    }
                                    else if((used[to] & 0x1F) == 0) {
                                        used[to] = (byte)(used[to] + 2 | 0x40);
                                    }
                                }
                                used[to] = (byte)(used[to] | 0x20);
                            }
                            else {
                                i = Print.NOP;
                            }
                            break;
                        }
                        case 3: {
                            if(pc == 0 || Print.GET_OPCODE(code[pc - 1]) != 2 || Print.GETARG_Ax(i) >= maxConst) {
                                i = Print.NOP;
                            }
                        }
                    }
                }
                if(i != orig) {
                    changed = true;
                }
                fixed[orig_pc] = i;
                ++pc;
            }
            entry = -1;
            for(int i = 0; i < code.length; ++i) {
                if((used[i] & 0x1F) == 2) {
                    entry = i;
                    break;
                }
            }
        }
        while(entry > 0);
        for(int pc = 0; pc < code.length; ++pc) {
            if((used[pc] & 0x1F) == 0) {
                int i = code[pc];
                int v21 = Print.GET_OPCODE(i);
                switch(v21) {
                    case 0x1F: {
                        if(pc == code.length - 1) {
                            i = Print.NOP;
                        }
                        else {
                            int v23 = Print.GETARG_A(i);
                            int v24 = Print.GETARG_B(i);
                            if(v24 < 0 || v23 >= maxVars || v23 + v24 - 2 >= maxVars || (used[pc - 1] & 0x1F) == 0) {
                                i = Print.NOP;
                            }
                        }
                        break;
                    }
                    case 23: 
                    case 0x20: 
                    case 33: 
                    case 35: {
                        int to = Print.GETARG_sBx(i) + pc + 1;
                        boolean out = to < 0 || to >= code.length;
                        if(!out) {
                            used[to] = (byte)(used[to] | 0x20);
                        }
                        if(v21 != 23) {
                            i = Print.NOP;
                        }
                        else if(!out && (used[to] & 0x1F) != 0 && (used[pc - 1] & 0x1F) != 0) {
                            switch(Print.GET_OPCODE(code[pc - 1])) {
                                case 23: 
                                case 0x1F: {
                                    i = Print.NOP;
                                }
                            }
                        }
                        else {
                            i = Print.NOP;
                        }
                        break;
                    }
                    default: {
                        i = Print.NOP;
                    }
                }
                if(i != Print.NOP || pc == code.length - 1) {
                    used[pc] = (byte)(used[pc] + 3);
                }
                if(!changed && i != code[pc]) {
                    changed = true;
                }
                fixed[pc] = i;
            }
        }
        return changed;
    }

    public static byte[] fix(Prototype f, int[] fixed) {
        int[] code = f.code;
        int n = code.length;
        if(fixed == null) {
            fixed = new int[n];
        }
        byte[] used = new byte[n + 2];
        for(int i = 0; i < 100 && Print.fix(used, f, code, fixed); ++i) {
            if(i == 0) {
                code = new int[n];
            }
            System.arraycopy(fixed, 0, code, 0, n);
            for(int j = 0; j < n; ++j) {
                used[j] = (byte)(used[j] & 0xFFFFFFE0);
            }
        }
        return used;
    }

    private static void format(String s, int maxcols) {
        int v1 = s.length();
        if(v1 > maxcols) {
            Print.ps.print(s.substring(0, maxcols));
            return;
        }
        Print.ps.print(s);
        int i = maxcols - v1;
        while(true) {
            --i;
            if(i < 0) {
                break;
            }
            Print.ps.print(' ');
        }
    }

    private static int getLine(Prototype f, int pc) {
        if(pc < 0) {
            return 0;
        }
        int[] lineinfo = f.lineinfo;
        if(lineinfo != null && pc < lineinfo.length) {
            int ret = lineinfo[pc];
            return ret >= 0 ? ret : 0;
        }
        return 0;
    }

    public static void print(Prototype prototype) {
        Print.ps.print("; --[=========[ Lua assembler file generated by GameGuardian " + 96.0f + " (" + 0x3E79 + ")\n");
        Print.printFunction(prototype, "", new PrintState());
        Print.ps.print("; ]=========] gg.require(\'" + 96.0f + "\', " + 0x3E79 + ")\n");
    }

    public static void printCode(Prototype f, String level, PrintState state) {
        state.level = level;
        PrintStream ps_ = Print.ps;
        int n = f.code.length;
        byte[] arr_b = Print.fix(f, null);
        state.used = arr_b;
        StringBuilder[] locals = new StringBuilder[n * 2];
        if(f.locvars != null && f.locvars.length > 0) {
            LocVars[] locvars = f.locvars;
            int[] stack = new int[locvars.length];
            int var = 0;
            for(int i = 0; i < locvars.length; ++i) {
                LocVars v = locvars[i];
                int endpc = v.endpc - 1;
                if(endpc >= v.startpc) {
                    for(int j = Math.min(var - 1, stack.length - 1); j >= 0 && stack[j] < v.startpc; --j) {
                        var = j;
                    }
                    stack[var] = endpc;
                    for(int j = 0; j < 2; ++j) {
                        int pc = j == 0 ? v.startpc : endpc;
                        if(pc < 0) {
                            pc = 0;
                        }
                        if(pc >= n) {
                            pc = n - 1;
                        }
                        int pc = pc * 2 + j;
                        StringBuilder sb = locals[pc];
                        if(sb == null) {
                            sb = new StringBuilder();
                            locals[pc] = sb;
                        }
                        sb.append(level);
                        sb.append((j == 0 ? ".local v" : ".end local v"));
                        sb.append(var);
                        sb.append(' ');
                        Print.printString(sb, v.varname);
                        sb.append('\n');
                    }
                    ++var;
                }
            }
        }
        int buf = n * 44 >= 0x2000 ? n * 44 : 0x2000;
        if(buf > 0x10000) {
            buf = 0x10000;
        }
        StringBuilder sb = new StringBuilder(buf);
        for(int pc = 0; pc < n; pc = pc + 1) {
            sb.append('\n');
            int use = arr_b[pc];
            if((use & 0x20) != 0) {
                sb.append(level);
                sb.append(":goto_");
                sb.append(pc);
                sb.append('\n');
            }
            StringBuilder local = locals[pc * 2];
            if(local != null) {
                sb.append(local);
                locals[pc * 2] = null;
            }
            sb.append(level);
            int pc = Print.printOpCode(sb, f, pc, state);
            switch(use & 0x1F) {
                case 0: {
                    sb.append(" ; garbage");
                    break;
                }
                case 3: {
                    sb.append(" ; unused");
                }
            }
            sb.append('\n');
            for(int tpc = pc; tpc <= pc; ++tpc) {
                for(int j = 0; j < 2; ++j) {
                    StringBuilder local = locals[tpc * 2 + j];
                    if(local != null) {
                        sb.append(local);
                        locals[tpc * 2 + j] = null;
                    }
                }
            }
            if(sb.length() > buf) {
                ps_.print(sb.toString());
                sb.setLength(0);
            }
        }
        if(sb.length() > 0) {
            ps_.print(sb.toString());
        }
    }

    static void printConstant(StringBuilder sb, Prototype f, int i) {
        if(i < f.k.length) {
            Print.printValue(sb, f.k[i]);
            return;
        }
        sb.append("CONST[");
        sb.append(i);
        sb.append("]");
    }

    public static void printFunction(Prototype prototype, String level, PrintState state) {
        Prototype[] p = prototype.p;
        Print.printHeader(prototype, level);
        Print.printUpValues(prototype, level);
        Print.printCode(prototype, level, state);
        int offset = state.func;
        state.func = offset + p.length;
        for(int i = 0; i < p.length; ++i) {
            Print.ps.print("\n");
            Print.ps.print(level);
            Print.ps.print(".func F" + (offset + i) + ' ');
            Print.printFunction(p[i], level + "\t", state);
            Print.ps.print(level);
            Print.ps.print(".end ; F" + (offset + i) + "\n");
        }
    }

    static void printHeader(Prototype f, String level) {
        StringBuilder stringBuilder0 = new StringBuilder(f.source.length() + 2);
        Print.printString(stringBuilder0, f.source);
        Print.ps.print("; " + f.upvalues.length + " upvalues, " + f.locvars.length + " locals, " + f.k.length + " constants, " + f.p.length + " funcs\n" + level + ".source " + stringBuilder0 + "\n" + level + ".linedefined " + f.linedefined + "\n" + level + ".lastlinedefined " + f.lastlinedefined + "\n" + level + ".numparams " + f.numparams + "\n" + level + ".is_vararg " + f.is_vararg + "\n" + level + ".maxstacksize " + f.maxstacksize + "\n");
    }

    public static int printOpCode(StringBuilder sb, Prototype f, int pc, PrintState state) {
        int max = f.maxstacksize;
        int upmax = f.upvalues.length;
        int[] code = f.code;
        int i = code[pc];
        int o = Print.GET_OPCODE(i);
        if(state != null) {
            int v5 = Print.getLine(f, pc);
            if(v5 != state.line) {
                state.line = v5;
                sb.append(".line ");
                sb.append(v5);
                sb.append('\n');
                sb.append(state.level);
            }
        }
        CharSequence comm = null;
        if(o < Print.OPNAMES.length - 1 && o != 39) {
            int v6 = Print.GETARG_A(i);
            int v7 = Print.GETARG_B(i);
            int c = Print.GETARG_C(i);
            int bx = Print.GETARG_Bx(i);
            int v10 = Print.GETARG_sBx(i);
            if(o == 2) {
                o = 1;
                if(pc + 1 >= code.length) {
                    bx = 0x7FFFFFFF;
                }
                else {
                    int i2 = code[pc + 1];
                    if(Print.GET_OPCODE(i2) == 39) {
                        ++pc;
                        bx = Print.GETARG_Ax(i2);
                    }
                    else {
                        bx = 0x7FFFFFFE;
                    }
                }
            }
            if(o == 33) {
                for(int j = 1; j <= 3; ++j) {
                    comm = Print.checkVar(((StringBuilder)comm), max, v6 + j);
                }
                if(state != null) {
                    for(int j = 0; j <= 3; ++j) {
                        sb.append("; .local v");
                        sb.append(v6 + j);
                        sb.append(" \"(for ");
                        switch(j) {
                            case 0: {
                                sb.append("index");
                                break;
                            }
                            case 1: {
                                sb.append("limit");
                                break;
                            }
                            case 2: {
                                sb.append("step");
                                break;
                            }
                            case 3: {
                                sb.append("iterator");
                            }
                        }
                        sb.append(")\"");
                        sb.append('\n');
                        sb.append(state.level);
                    }
                }
            }
            sb.append(Print.OPNAMES[o]);
            sb.append(' ');
        alab1:
            switch(Print.getOpMode(o)) {
                case 0: {
                    switch(o) {
                        case 8: {
                            sb.append('u');
                            comm = Print.checkUp(((StringBuilder)comm), upmax, v6);
                            break;
                        }
                        case 24: 
                        case 25: 
                        case 26: {
                            break;
                        }
                        default: {
                            sb.append('v');
                            comm = Print.checkVar(((StringBuilder)comm), max, v6);
                        }
                    }
                    sb.append(v6);
                    switch(o) {
                        case 4: {
                            sb.append("..v");
                            int v = v6 + v7;
                            sb.append(v);
                            comm = Print.checkVar(((StringBuilder)comm), max, v);
                            break alab1;
                        }
                        case 0x1F: {
                            if(v7 >= 2) {
                                sb.append("..v");
                                int v = v6 + v7 - 2;
                                sb.append(v);
                                comm = Print.checkVar(((StringBuilder)comm), max, v);
                            }
                            break alab1;
                        }
                        case 34: {
                            sb.append("..v");
                            int v = v6 + c + 2;
                            sb.append(v);
                            comm = Print.checkVar(((StringBuilder)comm), max, v);
                            break alab1;
                        }
                        case 36: {
                            if(v7 != 0) {
                                sb.append("..v");
                                int v = v6 + v7;
                                sb.append(v);
                                comm = Print.checkVar(((StringBuilder)comm), max, v);
                            }
                            sb.append(' ');
                            if(c == 0) {
                                if(pc >= code.length) {
                                    comm = Print.addComm(((StringBuilder)comm), "no OP after SETLIST with c = 0");
                                }
                                else {
                                    int next = code[pc + 1];
                                    comm = Print.addComm(((StringBuilder)comm), "c stored in next OP (as " + next + ")");
                                    if(next > 0 && (state == null || (state.used[pc + 1] & 0x60) == 0)) {
                                        ++pc;
                                        c = next;
                                    }
                                }
                            }
                            sb.append(c);
                            break alab1;
                        }
                        case 29: 
                        case 30: 
                        case 38: {
                            if(v7 != 0) {
                                sb.append("..v");
                                int v = v6 + v7 - 1;
                                sb.append(v);
                                comm = Print.checkVar(((StringBuilder)comm), max, v);
                            }
                            if(o == 29) {
                                if(c == 0) {
                                    sb.append(" SET_TOP");
                                }
                                else if(c > 1) {
                                    sb.append(" v");
                                    sb.append(v6);
                                    sb.append("..v");
                                    int v = v6 + c - 2;
                                    sb.append(v);
                                    comm = Print.checkVar(((StringBuilder)comm), max, v);
                                }
                            }
                            break alab1;
                        }
                        default: {
                            int v14 = Print.getBMode(o);
                            if(v14 != 0) {
                                sb.append(' ');
                                if(v14 != 3 || !Print.ISK(v7)) {
                                    if(o != 3 && o != 11) {
                                        if(v14 == 1) {
                                            sb.append('u');
                                            comm = Print.checkUp(((StringBuilder)comm), upmax, v7);
                                        }
                                        else {
                                            sb.append('v');
                                            comm = Print.checkVar(((StringBuilder)comm), max, v7);
                                        }
                                    }
                                    sb.append(v7);
                                }
                                else {
                                    Print.printConstant(sb, f, Print.INDEXK(v7));
                                }
                            }
                            if(o != 3) {
                                int v15 = Print.getCMode(o);
                                if(v15 != 0) {
                                    sb.append((o == 22 ? ".." : " "));
                                    if(v15 != 3 || !Print.ISK(c)) {
                                        if(v15 != 1) {
                                            sb.append('v');
                                            comm = Print.checkVar(((StringBuilder)comm), max, c);
                                        }
                                        sb.append(c);
                                    }
                                    else {
                                        Print.printConstant(sb, f, Print.INDEXK(c));
                                    }
                                }
                                if(o == 38 && f.is_vararg == 0) {
                                    comm = Print.addComm(((StringBuilder)comm), "func not vararg");
                                }
                            }
                            else if(c != 0) {
                                sb.append(" SKIP_NEXT");
                            }
                            break alab1;
                        }
                    }
                }
                case 1: {
                    sb.append('v');
                    comm = Print.checkVar(((StringBuilder)comm), max, v6);
                    sb.append(v6);
                    if(Print.getBMode(o) == 3) {
                        sb.append(' ');
                        if(bx == 0x7FFFFFFF) {
                            comm = Print.addComm(((StringBuilder)comm), "No OP after LOADKX");
                            bx = 0x3FFFF;
                        }
                        else if(bx == 0x7FFFFFFE) {
                            comm = Print.addComm(((StringBuilder)comm), "Next OP after LOADKX not EXTRAARG");
                            bx = 0x3FFFF;
                        }
                        Print.printConstant(sb, f, bx);
                    }
                    else {
                        sb.append(' ');
                        if(o != 37 || state == null) {
                            sb.append(bx);
                        }
                        else if(bx < f.p.length) {
                            sb.append('F');
                            sb.append(bx + state.func);
                        }
                        else {
                            sb.append("FUNC[");
                            sb.append(bx);
                            sb.append(']');
                        }
                    }
                    break;
                }
                case 2: {
                    if(o != 23 || v6 != 0) {
                        sb.append('v');
                        int v = o == 23 ? v6 - 1 : v6;
                        sb.append(v);
                        comm = Print.checkVar(((StringBuilder)comm), max, v);
                        sb.append(' ');
                    }
                    int to = v10 + pc + 1;
                    if(to >= 0 && to <= code.length) {
                        sb.append(":goto_");
                        sb.append(to);
                    }
                    else {
                        sb.append("GOTO[");
                        sb.append(v10);
                        sb.append("]");
                    }
                    sb.append("  ; ");
                    if(v10 >= 0) {
                        sb.append('+');
                    }
                    sb.append(v10);
                    sb.append(' ');
                    sb.append(((char)(v10 < 0 ? 8593 : 8595)));
                }
            }
            if(o == 0x20) {
                for(int j = 1; j <= 3; ++j) {
                    comm = Print.checkVar(((StringBuilder)comm), max, v6 + j);
                }
                if(state != null) {
                    if(comm == null) {
                        comm = new StringBuilder(0xA0);
                    }
                    for(int j = 0; j <= 3; ++j) {
                        ((StringBuilder)comm).append('\n');
                        ((StringBuilder)comm).append(state.level);
                        ((StringBuilder)comm).append("; .end local v");
                        ((StringBuilder)comm).append(v6 + j);
                        ((StringBuilder)comm).append(" \"(for ");
                        switch(j) {
                            case 0: {
                                ((StringBuilder)comm).append("index");
                                break;
                            }
                            case 1: {
                                ((StringBuilder)comm).append("limit");
                                break;
                            }
                            case 2: {
                                ((StringBuilder)comm).append("step");
                                break;
                            }
                            case 3: {
                                ((StringBuilder)comm).append("iterator");
                            }
                        }
                        ((StringBuilder)comm).append(")\"");
                    }
                }
            }
            if(o == 35) {
                for(int j = -2; j <= 1; ++j) {
                    if(j != 0) {
                        comm = Print.checkVar(((StringBuilder)comm), max, v6 + j);
                    }
                }
                if(state != null) {
                    if(comm == null) {
                        comm = new StringBuilder(0xA0);
                    }
                    for(int j = -2; j <= 1; ++j) {
                        ((StringBuilder)comm).append('\n');
                        ((StringBuilder)comm).append(state.level);
                        ((StringBuilder)comm).append("; .end local v");
                        ((StringBuilder)comm).append(v6 + j);
                        ((StringBuilder)comm).append(" \"(for ");
                        switch(j) {
                            case -2: {
                                ((StringBuilder)comm).append("generator");
                                break;
                            }
                            case -1: {
                                ((StringBuilder)comm).append("state");
                                break;
                            }
                            case 0: {
                                ((StringBuilder)comm).append("control");
                                break;
                            }
                            case 1: {
                                ((StringBuilder)comm).append("key");
                            }
                        }
                        ((StringBuilder)comm).append(")\"");
                    }
                }
            }
        }
        else {
            sb.append("OP[");
            sb.append(o);
            sb.append("] 0x");
            sb.append(Integer.toHexString(i));
        }
        if(comm != null) {
            sb.append("  ");
            sb.append(comm);
        }
        return pc;
    }

    public static int printOpCode(Prototype f, int pc) {
        StringBuilder sb = new StringBuilder();
        int v1 = Print.printOpCode(sb, f, pc, null);
        Print.ps.print(sb.toString());
        return v1;
    }

    public static void printStack(LuaValue[] stack, int top, Varargs varargs) {
        Print.ps.print('[');
        for(int i = 0; i < stack.length; ++i) {
            LuaValue v = stack[i];
            if(v == null) {
                Print.ps.print("null");
            }
            else if(v.type() == 4) {
                LuaString luaString0 = v.checkstring();
                Print.ps.print((luaString0.length() >= 0x30 ? luaString0.substring(0, 0x20).tojstring() + "...+" + (luaString0.length() - 0x20) + 'b' : luaString0.tojstring()));
            }
            else {
                Print.ps.print(v.tojstring());
            }
            if(i + 1 == top) {
                Print.ps.print(']');
            }
            Print.ps.print(" | ");
        }
        Print.ps.print(varargs);
    }

    public static void printState(LuaClosure cl, int pc, LuaValue[] stack, int top, Varargs varargs) {
        PrintStream prev = Print.ps;
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        Print.ps = new PrintStream(baos);
        Print.printOpCode(cl.p, pc);
        Print.ps.flush();
        Print.ps.close();
        Print.ps = prev;
        Print.format(baos.toString(), 50);
        Print.printStack(stack, top, varargs);
        Print.ps.println();
    }

    public static void printString(StringBuilder sb, LuaString s) {
        int n;
        if(s == null) {
            sb.append("nil");
            return;
        }
        sb.append('\"');
        char[] hexArr = HexText.hexArray;
        boolean z = s.isValidUtf8();
        byte[] m_bytes = null;
        String str = null;
        int m_offset = 0;
        if(z) {
            str = s.tojstring();
            n = str.length();
        }
        else {
            m_bytes = s.m_bytes;
            n = s.m_length;
            m_offset = s.m_offset;
        }
        for(int i = 0; i < n; ++i) {
            int v3 = z ? str.charAt(i) : ((char)m_bytes[m_offset + i]);
            if(v3 < 0x20 || v3 > 0x7E || v3 == 34 || v3 == 92) {
                switch(v3) {
                    case 7: {
                        sb.append('\\');
                        sb.append('a');
                        break;
                    }
                    case 8: {
                        sb.append('\\');
                        sb.append('b');
                        break;
                    }
                    case 9: {
                        sb.append('\\');
                        sb.append('t');
                        break;
                    }
                    case 10: {
                        sb.append('\\');
                        sb.append('n');
                        break;
                    }
                    case 11: {
                        sb.append('\\');
                        sb.append('v');
                        break;
                    }
                    case 12: {
                        sb.append('\\');
                        sb.append('f');
                        break;
                    }
                    case 13: {
                        sb.append('\\');
                        sb.append('r');
                        break;
                    }
                    case 34: 
                    case 92: {
                        sb.append('\\');
                        sb.append(((char)v3));
                        break;
                    }
                    default: {
                        if(!z || v3 < 0x20) {
                            sb.append("\\x");
                            sb.append(hexArr[(v3 & 0xF0) >> 4]);
                            sb.append(hexArr[v3 & 15]);
                        }
                        else {
                            sb.append(((char)v3));
                        }
                    }
                }
            }
            else {
                sb.append(((char)v3));
            }
        }
        sb.append('\"');
    }

    static void printUpValues(Prototype f, String level) {
        Upvaldesc[] upvalues = f.upvalues;
        if(upvalues.length == 0) {
            return;
        }
        StringBuilder sb = new StringBuilder();
        sb.append('\n');
        for(int i = 0; i < upvalues.length; ++i) {
            Upvaldesc uv = upvalues[i];
            sb.append(level);
            sb.append(".upval ");
            sb.append(((char)(uv.instack ? 0x76 : 0x75)));
            sb.append(((int)uv.idx));
            sb.append(' ');
            Print.printString(sb, uv.name);
            sb.append(" ; u");
            sb.append(i);
            sb.append('\n');
        }
        Print.ps.print(sb.toString());
    }

    static void printValue(StringBuilder sb, LuaValue v) {
        if(v == null) {
            sb.append("null");
            return;
        }
        if(v instanceof LuaLong) {
            sb.append(v.checklong());
            return;
        }
        if(v instanceof LuaDouble) {
            String s = Double.toString(v.checkdouble());
            sb.append(s);
            if(s.indexOf(46) < 0) {
                sb.append(".0");
                return;
            }
            return;
        }
        if(v.type() != 4) {
            sb.append(v.tojstring());
            return;
        }
        Print.printString(sb, ((LuaString)v));
    }

    public static void saveTail(LuaClosure func, String outFile) {
        int skip = func.p.tailPos;
        if(skip >= 0 && func.sourceFile != null) {
            File file0 = new File(func.sourceFile);
            if(file0.exists()) {
                try {
                    FileInputStream in = new FileInputStream(file0);
                    in.skip(((long)skip));
                    FileOutputStream out = new FileOutputStream(outFile);
                    byte[] buf = new byte[0x10000];
                    while(true) {
                        int v1 = in.read(buf);
                        if(v1 <= 0) {
                            out.close();
                            in.close();
                            return;
                        }
                        out.write(buf, 0, v1);
                    }
                }
                catch(IOException e) {
                    Log.d(("Fail save tail to " + outFile), e);
                }
            }
        }
    }
}

