package android.ext;

import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.content.pm.PackageManager.NameNotFoundException;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

public class Record extends Writer {
    final Consts consts;
    private final String file;
    private final Writer out;

    public Record(String file) throws IOException {
        File path = new File(file);
        File file1 = path.getParentFile();
        if(file1 != null) {
            file1.mkdirs();
        }
        this.file = file;
        this.out = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(path)));
        this.init();
        this.consts = Script.getConsts(null);
    }

    @Override
    public void close() throws IOException {
    }

    private void fail(String str, Throwable e) {
        Log.w(("Failed write text to record file: " + this.file + '\n' + str), e);
        this.stop();
        ThreadManager.runOnUiThread(new Runnable() {
            @Override
            public void run() {
                try {
                    Alert.show(Alert.create().setCustomTitle(Tools.getCustomTitle(0x7F0700AE)).setMessage(Record.this.file + "\n\n" + e.toString()).setPositiveButton(Re.s(0x7F07009D), null));  // string:error "Error"
                }
                catch(Throwable e) {
                    Log.w("Failed show alert", e);
                }
            }
        });
    }

    @Override
    public void flush() throws IOException {
    }

    public String getFile() {
        return this.file;
    }

    private void init() throws IOException {
        String start = "-- Script generated by GameGuardian %gg_ver% (%gg_build%) at %now% for %t_name% [%t_pkg% %t_ver% (%t_build%)]\n-- Lua help: http://gameguardian.net/help/\n\n-- options\nlocal scriptName = [=====[Script for %t_name% %t_ver%]=====]\nlocal scriptVersion = \'1.0.0\'\nlocal scriptAuthor = \'User\'\nlocal startToast = \'\'\n-- 0 - no check; 1 - check package only, 2 - check package and build\nlocal checkTarget = 0\n\nlocal targetName = [=====[%t_name%]=====]\nlocal targetPkg = \'%t_pkg%\'\nlocal targetVersion = [=====[%t_ver%]=====]\nlocal targetBuild = %t_build%\n\n-- functions\n\n-- init\ngg.require(\'%gg_ver%\', %gg_build%)\n\nif startToast ~= \'\' then startToast = \'\\n\'..startToast end\ngg.toast(scriptName..\' v\'..scriptVersion..\' by \'..scriptAuthor..startToast)\n\nif checkTarget ~= 0 then\n\tlocal info = gg.getTargetInfo()\n\tlocal check = false\n\tlocal current = false\n\tif checkTarget >= 1 then\n\t\tcheck = targetPkg\n\t\tcurrent = info.packageName\n\tend\n\tif checkTarget >= 2 then\n\t\tcheck = check..\' \'..targetVersion..\' (\'..targetBuild..\')\'\n\t\tcurrent = current..\' \'..info.versionName..\' (\'..info.versionCode..\')\'\n\tend\n\tif check ~= current then\n\t\tgg.alert(\'This script for \"\'..targetName..\'\" [\'..check..\'].\\nYou select \"\'..info.label..\'\" [\'..current..\'].\\nNow script exit.\')\n\t\tos.exit()\n\tend\nend\nlocal revert = nil\n\n-- main code\n".replace("%gg_ver%", 96.0f).replace("%gg_build%", "15993").replace("%now%", new SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.US).format(new Date()));
        ProcessInfo pi = MainService.instance.processInfo;
        if(pi != null) {
            String pkg = pi.packageName;
            start = start.replace("%t_pkg%", pkg);
            try {
                PackageInfo packageInfo0 = Tools.getPackageInfo(pkg, 0);
                if(packageInfo0 != null) {
                    if(packageInfo0.versionName != null) {
                        start = start.replace("%t_ver%", packageInfo0.versionName);
                    }
                    start = start.replace("%t_build%", Integer.toString(packageInfo0.versionCode));
                    ApplicationInfo ai = packageInfo0.applicationInfo;
                    if(ai != null) {
                        String s2 = Tools.getApplicationLabel(ai);
                        if(s2 != null) {
                            start = start.replace("%t_name%", s2);
                        }
                    }
                }
            }
            catch(PackageManager.NameNotFoundException e) {
                Log.w(("Pkg not found: " + pkg), e);
            }
        }
        this.out.write(start);
    }

    public void stop() {
        MainService.instance.onRecordEnd(this);
        try {
            this.out.close();
        }
        catch(IOException e) {
            Log.w(("Failed close record to: " + this.file), e);
        }
        Tools.showToast((Tools.stripColon(0x7F0702E7) + ": " + this.file));  // string:record_ended "Recording completed:"
    }

    @Override
    public void write(String str) {
        try {
            this.out.write(str);
        }
        catch(Throwable e) {
            this.fail(str, e);
        }
    }

    @Override
    public void write(char[] cbuf, int off, int len) throws IOException {
    }
}

