name: Build Luaj Jar

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Ant
      run: ant all

    - name: Upload JAR Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: luaj-jars
        path: |
          luaj-jse-*.jar
          luaj-sources-*.jar
